### ISSUE TITLE
Jdbc connector no longer needs to serialize and deserialize ConnecRecord objects

### ISSUE THREAD

**Issue by odbozhou** [apache/rocketmq-connect#209]
![image](https://user-images.githubusercontent.com/14222167/180152418-6a0462c8-a64d-4359-906a-8a1a55fbe02a.png)

**BUG REPORT**

1. Please describe the issue you observed:

jdbc connector no longer needs to serialize and deserialize ConnecRecord objects。

- What did you do (The steps to reproduce)?

- What is expected to see?

- What did you see instead?

3. Please tell us about your environment:

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

5. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Valid (Stale)**

The JDBC connector should not need to serialize/deserialize `ConnectRecord` objects if it works directly with the in-memory representation. This is a valid optimization.

Open since July 2022. If the current JDBC connector still performs unnecessary serialization, a PR to streamline the record handling would be welcome.

---
*Automated evaluation by RockteMQ-AI*
