### ISSUE TITLE
There are many unreadable methods

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq-connect#244]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

In `org.apache.rocketmq.connect.runtime.errors.ProcessingContext`

There are many methods to get parameters without get, and many methods to set parameters without set

> 

      /**
     * Set the record consumed from Kafka in a sink connector.
     *
     * @param consumedMessage the record
     */
    public void consumerRecord(MessageExt consumedMessage) {
        this.consumedMessage = consumedMessage;
        reset();
    }

    /**
     * @return the record consumed from Kafka. could be null
     */
    public MessageExt consumerRecord() {
        return consumedMessage;
    }

    /**
     * @return the source record being processed.
     */
    public ConnectRecord sourceRecord() {
        return sourceRecord;
    }

    /**
     * Set the source record being processed in the connect pipeline.
     *
     * @param record the source record
     */
    public void sourceRecord(ConnectRecord record) {
        this.sourceRecord = record;
        reset();
    }

    /**
     * Set the stage in the connector pipeline which is currently executing.
     *
     * @param stage the stage
     */
    public void stage(ErrorReporter.Stage stage) {
        this.stage = stage;
    }

    /**
     * @return the stage in the connector pipeline which is currently executing.
     */
    public ErrorReporter.Stage stage() {
        return stage;
    }

    /**
     * @return the class which is going to execute the current operation.
     */
    public Class<?> executingClass() {
        return klass;
    }

    /**
     * @param klass set the class which is currently executing.
     */
    public void executingClass(Class<?> klass) {
        this.klass = klass;
    }

- What is expected to see?

Get is added to the method of getting parameters, and set is added to the method of setting parameters

- What did you see instead?

There are many unreadable methods

2. Please tell us about your environment:

master

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

What do you think ? @sunxiaojian

**Comment by sunxiaojian** [comment]
> There are many methods to get parameters without get, and many methods to set parameters without set
> 
> >

If you do not use JSON for serialization, you should not impose restrictions on the declaration of methods; However, the same project will consider declaring in the same way

**Comment by Oliverwqcwrw** [comment]
Get it, thanks for your reply

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Already Addressed**

This issue was discussed and resolved in August 2022. The maintainer clarified that method naming conventions (get/set prefixes) should not be enforced when JSON serialization is not used, and that consistency within the same project is the guiding principle.

The original author acknowledged the response. No further action is needed.

This issue can be closed by a maintainer at their discretion.

---
*Automated evaluation by github-manager*

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Already Addressed**

This issue was discussed and resolved in August 2022. The maintainer clarified that method naming conventions (get/set prefixes) should not be enforced when JSON serialization is not used, and that consistency within the same project is the guiding principle.

The original author acknowledged the response. No further action is needed.

This issue can be closed by a maintainer at their discretion.

---
*Automated evaluation by github-manager*
