### ISSUE TITLE
Boolean.getBoolean always return false

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq-connect#253]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

In `org.apache.rocketmq.connect.runtime.errors.DeadLetterQueueConfig#isDlqContextHeadersEnabled`

Boolean.getBoolean always return false because we don't set system property

- What is expected to see?

get property from ConnectKeyValue

- What did you see instead?

get property from system property

2. Please tell us about your environment:

master

4. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

replace Boolean.getBoolean to Boolean.valueOf

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Confirmed**

This is a valid bug. `Boolean.getBoolean(String)` reads a **system property** and returns `true` only if that property exists and equals `"true"` (case-insensitive). It does **not** parse the string value itself.

If the intent is to parse a string like `"true"`/`"false"` into a boolean, the correct method is `Boolean.valueOf(String)` or `Boolean.parseBoolean(String)`.

**Root Cause:** Incorrect API usage — `Boolean.getBoolean()` vs `Boolean.valueOf()`
**Impact:** Configuration values that should be parsed as booleans will always return `false` unless a matching system property is set
**Severity:** Medium

A fix should replace `Boolean.getBoolean(...)` with `Boolean.valueOf(...)` or `Boolean.parseBoolean(...)` depending on context.

---
*Automated evaluation by RockteMQ-AI*
