### ISSUE TITLE
fix the error when building the project

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq-connect#45]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
build the project 
- What is expected to see?
build success
- What did you see instead?
![image](https://user-images.githubusercontent.com/25401190/161374604-5294f258-46b1-407c-9043-787b312b4e1b.png)

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks involved, use -[] for each sub-task and create a corresponding issue to map to the sub-task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by odbozhou** [comment]
merged

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Evaluated**

This reports a build failure when building the project. The screenshot in the original issue is no longer accessible.

Note: This issue has been open since April 2022. The build system and dependencies have likely been updated since then. A maintainer should verify if the build still fails with the current codebase.

---
*Automated evaluation by RockteMQ-AI*
