### ISSUE TITLE
openmessaging-connector version is wrong

### ISSUE THREAD

**Issue by youngkangrui** [apache/rocketmq-connect#48]
Could not resolve dependencies for project org.apache.rocketmq:rocketmq-connect-sample:jar:0.0.1-SNAPSHOT: Could not find artifact io.openmessaging:openmessaging-connector:jar:0.1.2-SNAPSHOT

**Comment by odbozhou** [comment]
是的，这个问题正在解决中，请先将这个最新的api  https://github.com/openmessaging/openconnect/pull/37
本地install

**Comment by Slideee** [comment]
> 是的，这个问题正在解决中，请先将这个最新的api [openmessaging/openconnect#37](https://github.com/openmessaging/openconnect/pull/37) 本地install

请问openconnect现在是用0.1.2还是0.1.3呢

**Comment by odbozhou** [comment]
please use 0.1.2

**Comment by odbozhou** [comment]
The version problem has been solved, please update the latest code

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Evaluated**

This reports a dependency resolution failure: `openmessaging-connector:jar:0.1.2-SNAPSHOT` cannot be found. This is likely because the SNAPSHOT artifact is no longer available in the repository.

Note: This issue has been open since April 2022. The dependency versions have likely been updated since then. A maintainer should verify if this is still reproducible with the current codebase.

---
*Automated evaluation by RockteMQ-AI*
