### ISSUE TITLE
Some parameters of FileSourceConnector and  FileSinkConnector in readme is inconsistent.

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq-connect#49]
Some parameters of FileSourceConnector and  FileSinkConnector in readme is inconsistent.

**Comment by odbozhou** [comment]
merged

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `documentation` | Status: **Evaluated**

This issue reports inconsistent parameters between `FileSourceConnector` and `FileSinkConnector` in the README documentation. This is a valid documentation fix.

Note: This issue has been open since April 2022. If the documentation has already been corrected in a later update, this issue can be closed by a maintainer.

---
*Automated evaluation by RockteMQ-AI*
